// Auto-generated by scripts/build-tokens.js — do not edit manually.

export const cssTokens = {
    primary: 'var(--pnpnm-primary)',  // #4d49fc
    hover: 'var(--pnpnm-hover)',  // hsl(from var(--pnpnm-primary) h s l / 80%)
    secondary: 'var(--pnpnm-secondary)',  // hsl(from var(--pnpnm-primary) h s l / 18%)
    light: 'var(--pnpnm-light)',  // hsl(from var(--pnpnm-primary) h s l / 11%)
    extralight: 'var(--pnpnm-extralight)',  // hsl(from var(--pnpnm-primary) h s l / 5%)
    descgray: 'var(--pnpnm-descgray)',  // #979797
    warning: 'var(--pnpnm-warning)',  // #ff5900
    warninglight: 'var(--pnpnm-warninglight)',  // #ff590033
    warningextralight: 'var(--pnpnm-warningextralight)',  // #ff59001a
    error: 'var(--pnpnm-error)',  // #ff0000
    errorlight: 'var(--pnpnm-errorlight)',  // #ff000033
    errorextralight: 'var(--pnpnm-errorextralight)',  // #ff00001a
    pro: 'var(--pnpnm-pro)',  // #ffc300
    new: 'var(--pnpnm-new)',  // #e3eeff
} as const;

export type CssToken = keyof typeof cssTokens;
