export type FileContextMenu =
    | "open"
    | "view"
    | "get"
    | "edit"
    | "download"
    | "duplicate"
    | "replace"
    | "favorite"
    | "unfavorite"
    | "apply"
    | "remove"
    | "trash"
    | "restore"
    | "delete";
