<?php
/**
 * Image Tools admin page — adds "Image Tools" as a submenu of the Ninja Media
 * plugin menu (same parent as File Manager / Settings / Watermark).
 *
 * Hook produced by WordPress: ninja-media_page_pnpnm-image-tools
 * This hook contains PNPNM_SLUG so Enqueue::isPluginPage() catches it and
 * loads the shared `pnpnm` localize object (restUrl + nonce) automatically.
 *
 * @package Pninja\NM\Modules
 */

namespace Pninja\NM\Modules;

defined( 'ABSPATH' ) || exit;

class ImageToolsAdmin {

	/** Hook suffix generated by WordPress for this page. */
	public const HOOK = 'ninja-media_page_pnpnm-image-tools';

	public function __construct() {
		$this->doHooks();
	}

	public function doHooks(): void {
		add_action( 'admin_menu', array( $this, 'add_menu_page' ) );
	}

	public static function isSettingsPage( string $hook ): bool {
		return self::HOOK === $hook;
	}

	public function add_menu_page(): void {
		add_submenu_page(
			PNPNM_SLUG,
			__( 'Image Tools', 'ninja-media' ),
			__( 'Image Tools', 'ninja-media' ),
			'upload_files',
			'pnpnm-image-tools',
			array( $this, 'render_page' )
		);
	}

	public function render_page(): void {
		if ( ! current_user_can( 'upload_files' ) ) {
			wp_die( esc_html__( 'You do not have permission to access this page.', 'ninja-media' ) );
		}

		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only tab param.
		$active_tab = isset( $_GET['tab'] ) ? sanitize_key( $_GET['tab'] ) : 'optimizer';
		$allowed    = array( 'optimizer', 'editor' );
		if ( ! in_array( $active_tab, $allowed, true ) ) {
			$active_tab = 'optimizer';
		}

		$base_url = admin_url( 'admin.php?page=pnpnm-image-tools' );
		?>
		<div class="wrap pnpnm-image-tools">
			<h1><?php esc_html_e( 'Image Tools', 'ninja-media' ); ?></h1>

			<nav class="nav-tab-wrapper">
				<a href="<?php echo esc_url( $base_url . '&tab=optimizer' ); ?>"
				   class="nav-tab<?php echo 'optimizer' === $active_tab ? ' nav-tab-active' : ''; ?>">
					<?php esc_html_e( 'Image Optimizer', 'ninja-media' ); ?>
				</a>
				<a href="<?php echo esc_url( $base_url . '&tab=editor' ); ?>"
				   class="nav-tab<?php echo 'editor' === $active_tab ? ' nav-tab-active' : ''; ?>">
					<?php esc_html_e( 'Image Editor Settings', 'ninja-media' ); ?>
				</a>
			</nav>

			<div class="pnpnm-tab-content">
				<?php if ( 'optimizer' === $active_tab ) : ?>
					<?php $this->render_optimizer_tab(); ?>
				<?php else : ?>
					<?php $this->render_editor_tab(); ?>
				<?php endif; ?>
			</div>
		</div>
		<?php
	}

	// -------------------------------------------------------------------------
	// Optimizer tab
	// -------------------------------------------------------------------------

	private function render_optimizer_tab(): void {
		$raw      = get_option( 'pnpnm_optimizer_settings', array() );
		$settings = wp_parse_args( $raw, array(
			'quality'        => 82,
			'type'           => 'lossy',
			'auto_optimize'  => false,
			'keep_backup'    => true,
			'convert_webp'   => false,
			'strip_metadata' => false,
		) );
		?>
		<div class="pnpnm-settings-form" id="pnpnm-optimizer-settings">
			<h2><?php esc_html_e( 'Optimizer Settings', 'ninja-media' ); ?></h2>

			<table class="form-table" role="presentation">
				<tr>
					<th scope="row">
						<label for="pnpnm-quality"><?php esc_html_e( 'Quality', 'ninja-media' ); ?></label>
					</th>
					<td>
						<input type="number" id="pnpnm-quality" name="quality"
							min="60" max="100"
							value="<?php echo esc_attr( $settings['quality'] ); ?>"
							class="small-text">
						<p class="description"><?php esc_html_e( '60–100. Lower = smaller file, lower quality.', 'ninja-media' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row">
						<label for="pnpnm-type"><?php esc_html_e( 'Compression Type', 'ninja-media' ); ?></label>
					</th>
					<td>
						<select id="pnpnm-type" name="type">
							<option value="lossy" <?php selected( $settings['type'], 'lossy' ); ?>>
								<?php esc_html_e( 'Lossy', 'ninja-media' ); ?>
							</option>
							<option value="lossless" <?php selected( $settings['type'], 'lossless' ); ?>>
								<?php esc_html_e( 'Lossless', 'ninja-media' ); ?>
							</option>
						</select>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Auto-optimize on Upload', 'ninja-media' ); ?></th>
					<td>
						<label>
							<input type="checkbox" name="auto_optimize" value="1"
								<?php checked( $settings['auto_optimize'] ); ?>>
							<?php esc_html_e( 'Automatically optimize new images when uploaded', 'ninja-media' ); ?>
						</label>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Keep Original Backup', 'ninja-media' ); ?></th>
					<td>
						<label>
							<input type="checkbox" name="keep_backup" value="1"
								<?php checked( $settings['keep_backup'] ); ?>>
							<?php esc_html_e( 'Save a backup of the original image so you can restore it later', 'ninja-media' ); ?>
						</label>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Convert to WebP', 'ninja-media' ); ?></th>
					<td>
						<label>
							<input type="checkbox" name="convert_webp" value="1"
								<?php checked( $settings['convert_webp'] ); ?>>
							<?php esc_html_e( 'Generate a .webp copy alongside each optimized image (requires GD WebP support)', 'ninja-media' ); ?>
						</label>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Strip Hidden Metadata', 'ninja-media' ); ?></th>
					<td>
						<label>
							<input type="checkbox" name="strip_metadata" value="1"
								<?php checked( $settings['strip_metadata'] ); ?>>
							<?php esc_html_e( 'Remove EXIF, IPTC, and XMP metadata from images during optimization', 'ninja-media' ); ?>
						</label>
						<p class="description">
							<?php esc_html_e( 'Metadata is stripped automatically when images are re-encoded via GD. This reduces file size and removes GPS coordinates, camera info, and other embedded data.', 'ninja-media' ); ?>
						</p>
					</td>
				</tr>
			</table>

			<p class="submit">
				<button type="button" class="button button-primary" id="pnpnm-save-optimizer">
					<?php esc_html_e( 'Save Settings', 'ninja-media' ); ?>
				</button>
				<span class="pnpnm-save-msg" id="pnpnm-optimizer-save-msg" aria-live="polite"></span>
			</p>
		</div>

		<hr>

		<div class="pnpnm-strip-metadata" id="pnpnm-strip-metadata-section">
			<h2><?php esc_html_e( 'Strip Hidden Metadata', 'ninja-media' ); ?></h2>
			<p><?php esc_html_e( 'Remove EXIF, IPTC, XMP, and other hidden data from all images in your library. This is irreversible unless you have Keep Original Backup enabled.', 'ninja-media' ); ?></p>

			<div class="pnpnm-bulk-controls">
				<button type="button" class="button button-secondary" id="pnpnm-strip-start">
					<?php esc_html_e( 'Strip Metadata from All Images', 'ninja-media' ); ?>
				</button>
				<button type="button" class="button pnpnm-hidden" id="pnpnm-strip-stop">
					<?php esc_html_e( 'Stop', 'ninja-media' ); ?>
				</button>
			</div>

			<div class="pnpnm-progress-wrap pnpnm-hidden" id="pnpnm-strip-progress-wrap">
				<label for="pnpnm-strip-progress-bar" class="pnpnm-progress-label" id="pnpnm-strip-progress-label">
					<?php esc_html_e( 'Starting…', 'ninja-media' ); ?>
				</label>
				<progress id="pnpnm-strip-progress-bar" class="pnpnm-progress" value="0" max="100"></progress>
			</div>

			<div class="pnpnm-bulk-results pnpnm-hidden" id="pnpnm-strip-results">
				<table class="widefat striped pnpnm-results-table">
					<thead>
						<tr>
							<th><?php esc_html_e( 'Attachment ID', 'ninja-media' ); ?></th>
							<th><?php esc_html_e( 'Size Before', 'ninja-media' ); ?></th>
							<th><?php esc_html_e( 'Size After', 'ninja-media' ); ?></th>
							<th><?php esc_html_e( 'Bytes Saved', 'ninja-media' ); ?></th>
						</tr>
					</thead>
					<tbody id="pnpnm-strip-results-body"></tbody>
				</table>
			</div>
		</div>

		<hr>

		<div class="pnpnm-bulk-optimizer" id="pnpnm-bulk-optimizer">
			<h2><?php esc_html_e( 'Bulk Optimizer', 'ninja-media' ); ?></h2>

			<div class="pnpnm-bulk-stats" id="pnpnm-bulk-stats">
				<span class="pnpnm-stat-item">
					<?php esc_html_e( 'Total images:', 'ninja-media' ); ?>
					<strong id="pnpnm-stat-total">—</strong>
				</span>
				<span class="pnpnm-stat-item">
					<?php esc_html_e( 'Optimized:', 'ninja-media' ); ?>
					<strong id="pnpnm-stat-optimized">—</strong>
				</span>
				<span class="pnpnm-stat-item">
					<?php esc_html_e( 'Unoptimized:', 'ninja-media' ); ?>
					<strong id="pnpnm-stat-unoptimized">—</strong>
				</span>
				<span class="pnpnm-stat-item">
					<?php esc_html_e( 'Total savings:', 'ninja-media' ); ?>
					<strong id="pnpnm-stat-savings">—</strong>
				</span>
			</div>

			<div class="pnpnm-bulk-controls">
				<button type="button" class="button button-primary" id="pnpnm-bulk-start">
					<?php esc_html_e( 'Start Bulk Optimization', 'ninja-media' ); ?>
				</button>
				<button type="button" class="button pnpnm-hidden" id="pnpnm-bulk-stop">
					<?php esc_html_e( 'Stop', 'ninja-media' ); ?>
				</button>
			</div>

			<p class="pnpnm-hidden pnpnm-empty-notice" id="pnpnm-no-images-msg">
				<?php esc_html_e( 'All images are already optimized — nothing left to process.', 'ninja-media' ); ?>
			</p>

			<div class="pnpnm-progress-wrap pnpnm-hidden" id="pnpnm-progress-wrap">
				<label for="pnpnm-progress-bar" class="pnpnm-progress-label" id="pnpnm-progress-label">
					<?php esc_html_e( 'Starting…', 'ninja-media' ); ?>
				</label>
				<progress id="pnpnm-progress-bar" class="pnpnm-progress" value="0" max="100"></progress>
			</div>

			<div class="pnpnm-bulk-results pnpnm-hidden" id="pnpnm-bulk-results">
				<table class="widefat striped pnpnm-results-table">
					<thead>
						<tr>
							<th><?php esc_html_e( 'Filename', 'ninja-media' ); ?></th>
							<th><?php esc_html_e( 'Original Size', 'ninja-media' ); ?></th>
							<th><?php esc_html_e( 'Optimized Size', 'ninja-media' ); ?></th>
							<th><?php esc_html_e( 'Savings', 'ninja-media' ); ?></th>
						</tr>
					</thead>
					<tbody id="pnpnm-results-body"></tbody>
				</table>
			</div>
		</div>
		<?php
	}

	// -------------------------------------------------------------------------
	// Editor settings tab
	// -------------------------------------------------------------------------

	private function render_editor_tab(): void {
		$raw      = get_option( 'pnpnm_editor_settings', array() );
		$settings = wp_parse_args( $raw, array(
			'default_save_mode' => 'new',
			'default_format'    => 'jpeg',
		) );
		?>
		<div class="pnpnm-settings-form" id="pnpnm-editor-settings">
			<h2><?php esc_html_e( 'Image Editor Defaults', 'ninja-media' ); ?></h2>

			<table class="form-table" role="presentation">
				<tr>
					<th scope="row">
						<label for="pnpnm-default-save-mode"><?php esc_html_e( 'Default Save Mode', 'ninja-media' ); ?></label>
					</th>
					<td>
						<select id="pnpnm-default-save-mode" name="default_save_mode">
							<option value="new" <?php selected( $settings['default_save_mode'], 'new' ); ?>>
								<?php esc_html_e( 'Save as New Attachment', 'ninja-media' ); ?>
							</option>
							<option value="replace" <?php selected( $settings['default_save_mode'], 'replace' ); ?>>
								<?php esc_html_e( 'Replace Original', 'ninja-media' ); ?>
							</option>
						</select>
					</td>
				</tr>
				<tr>
					<th scope="row">
						<label for="pnpnm-default-format"><?php esc_html_e( 'Default Export Format', 'ninja-media' ); ?></label>
					</th>
					<td>
						<select id="pnpnm-default-format" name="default_format">
							<option value="jpeg" <?php selected( $settings['default_format'], 'jpeg' ); ?>>JPEG</option>
							<option value="png"  <?php selected( $settings['default_format'], 'png' ); ?>>PNG</option>
						</select>
					</td>
				</tr>
			</table>

			<p class="submit">
				<button type="button" class="button button-primary" id="pnpnm-save-editor">
					<?php esc_html_e( 'Save Settings', 'ninja-media' ); ?>
				</button>
				<span class="pnpnm-save-msg" id="pnpnm-editor-save-msg" aria-live="polite"></span>
			</p>
		</div>
		<?php
	}
}
