/**
 * build-tokens.js
 *
 * Reads CSS custom-property declarations from
 *   source/assets/sass/utilities/_variable.scss
 * and writes two outputs:
 *
 *   1. source/constants/cssTokens.ts  — typed TS object for use in React components
 *   2. assets/css/tokens.css          — standalone CSS file with :root variables
 *
 * Run via: npm run build:tokens
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname( fileURLToPath( import.meta.url ) );
const root      = join( __dirname, '..' );

// ── Read source ───────────────────────────────────────────────────────────────

const scssPath = join( root, 'source/assets/sass/utilities/_variable.scss' );
const scss     = readFileSync( scssPath, 'utf8' );

// Extract the :root { ... } block (first occurrence only — global tokens).
const rootMatch = scss.match( /:root\s*\{([^}]+)\}/s );
if ( ! rootMatch ) {
    console.error( '[build-tokens] Could not find :root block in _variable.scss' );
    process.exit( 1 );
}

const rootBlock = rootMatch[ 1 ];

// Parse --pnpnm-* custom properties.
const tokenRegex = /--(pnpnm-[\w-]+)\s*:\s*([^;]+);/g;
const tokens     = {};
let match;

while ( ( match = tokenRegex.exec( rootBlock ) ) !== null ) {
    const key   = match[ 1 ].trim();
    const value = match[ 2 ].trim();
    // Skip SCSS comments and HSL relative-color expressions (browser-computed).
    if ( ! value.startsWith( '//' ) ) {
        tokens[ key ] = value;
    }
}

const tokenCount = Object.keys( tokens ).length;

// ── Write 1: TypeScript constants ─────────────────────────────────────────────

const tsDir  = join( root, 'source/constants' );
const tsPath = join( tsDir, 'cssTokens.ts' );

mkdirSync( tsDir, { recursive: true } );

const tsLines = [
    '// Auto-generated by scripts/build-tokens.js — do not edit manually.',
    '',
    'export const cssTokens = {',
    ...Object.entries( tokens ).map( ( [ k, v ] ) => {
        const prop = k.replace( /^pnpnm-/, '' ).replace( /-([a-z])/g, ( _, c ) => c.toUpperCase() );
        return `    ${ prop }: 'var(--${ k })',  // ${ v }`;
    } ),
    '} as const;',
    '',
    'export type CssToken = keyof typeof cssTokens;',
    '',
];

writeFileSync( tsPath, tsLines.join( '\n' ), 'utf8' );

// ── Write 2: Standalone tokens CSS ───────────────────────────────────────────

const cssDir  = join( root, 'assets/css' );
const cssPath = join( cssDir, 'tokens.css' );

mkdirSync( cssDir, { recursive: true } );

const cssLines = [
    '/* Auto-generated by scripts/build-tokens.js — do not edit manually. */',
    ':root {',
    ...Object.entries( tokens ).map( ( [ k, v ] ) => `    --${ k }: ${ v };` ),
    '}',
    '',
];

writeFileSync( cssPath, cssLines.join( '\n' ), 'utf8' );

// ── Done ──────────────────────────────────────────────────────────────────────

console.log( `[build-tokens] ✓ ${ tokenCount } tokens written to:` );
console.log( `               ${ tsPath.replace( root, '.' ) }` );
console.log( `               ${ cssPath.replace( root, '.' ) }` );
